# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: /media/ubuntu/new1/msy/dataset/ntu120/xsetup/val_data_joint_motion.npy
  label_path: /media/ubuntu/new1/msy/dataset/ntu120/xsetup/val_label.pkl
  debug: False

# model
model: model.shift_gcn.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0, 1]
test_batch_size: 256
weights: ./save120/save_models/ntu_cs_agcn_joint-49-31300.pt

Experiment_name: ntu120_CDGC_joint_motion_xsetup
save_score: True
