# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: /media/ubuntu/new1/msy/dataset/ntu60/xview/val_data_bone_motion.npy
  label_path: /media/ubuntu/new1/msy/dataset/ntu60/xview/val_label.pkl
  debug: False

# model
model: model.shift_gcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0, 1]
test_batch_size: 256
weights: ./save120/save_models11/ntu120_ShiftGCN_bone_motion_xsub-107-141804.pt

Experiment_name: ntu_CDGC_bone_motion_xview
save_score: True
