# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: /media/ubuntu/new1/msy/dataset/ntu/xview/val_data_joint.npy
  label_path: /media/ubuntu/new1/msy/dataset/ntu/xview/val_label.pkl
  debug: False

# model
model: model.shift_gcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0, 1]
test_batch_size: 256
weights: /media/ubuntu/new1/msy/code/Shift-GCN-master/Untitled Folder/save_models3/ntu_ShiftGCN_joint_xview-1-1568.pt

Experiment_name: ntu_CDGC_joint_xview
save_score: True
