# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: /media/ubuntu/new1/msy/dataset/ntu/xsub/val_data_bone.npy
  label_path: /media/ubuntu/new1/msy/dataset/ntu/xsub/val_label.pkl
  debug: False

# model
model: model.shift_gcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0, 1]
test_batch_size: 256
weights: /media/ubuntu/new1/msy/code/Shift-GCN0_save/save_models10/ntu_ShiftGCN_bone_xsub-139-116900.pt

Experiment_name: ntu60_CDGC_bone_xsub
save_score: True
