Experiment_name: ntu_CDGC_joint_xsub

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /media/ubuntu/new1/msy/dataset/ntu/xsub/train_data_joint.npy
  label_path: /media/ubuntu/new1/msy/dataset/ntu/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /media/ubuntu/new1/msy/dataset/ntu/xsub/val_data_joint.npy
  label_path: /media/ubuntu/new1/msy/dataset/ntu/xsub/val_label.pkl

# model
model: model.shift_gcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [60, 80, 100]

# training
device: [0,1]
only_train_epoch: 1
batch_size: 48
test_batch_size: 48
num_epoch: 140
nesterov: True
